### ISSUE TITLE
Interface crashes when certain floats are used

### ISSUE THREAD

**Issue by averycrespi** [levmckinney/yoloxide-web#1]
### How to reproduce

Go to https://yoloxide.cylon.xyz/networks

Create a new device.

Enter any of the following lines into the device:
- `foo = NaN`
- `foo = infinity`
- `foo = -infinity`

### What happens

The app crashes.

### What should happen

The app doesn't crash.

**Comment by levmckinney** [comment]
Cant seem to replicate the crash for me it just sets the variable to 0.

**Comment by averycrespi** [comment]
Seems to be fixed. Maybe Matrix did something?
