### ISSUE TITLE
Type: "dose" should be "does"

### ISSUE THREAD

**Issue by ocornoc** [levmckinney/yoloxide-web#12]
**Describe the bug**
"does" is spelt as "dose".

**To Reproduce**
Try setting any external field that's not declared.

**Expected behavior**
"does"

**Screenshots**
![image](https://user-images.githubusercontent.com/25855126/65274854-23822180-dad9-11e9-9b83-fb6b7e63d1e8.png)

**Comment by levmckinney** [comment]
cec14c9bb78149ece5966d80e452f6bdca588422
