### ISSUE TITLE
Line halts on error

### ISSUE THREAD

**Issue by averycrespi** [levmckinney/yoloxide-web#2]
### Steps to reproduce

Create a new device, with contents:

```
*
foo = 1
```

Click `Run`.

### What happens

The line number stays at 1 forever, and line 2 never executes.

### What should happen

Line 1 should be skipped and the program should continue.

**Comment by Jerald** [comment]
Parse errors will still fail on the backend. But runtime errors are now handled correctly.

@levmckinney add a message on the frontend for errors produced by the backend, notably warning people if they have a parse error.

**Comment by levmckinney** [comment]
Warnings were added for all errors in 82b9967d6f288a5b197af44f718f6acdae446172
